"""auto update

Revision ID: fc006de34304
Revises: 
Create Date: 2026-04-18 09:20:25.324297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc006de34304'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('paciente_nombre', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('notas', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expediente', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('peso', sa.String(), nullable=True),
    sa.Column('talla', sa.String(), nullable=True),
    sa.Column('procedimiento', sa.String(), nullable=True),
    sa.Column('comorbilidades', sa.String(), nullable=True),
    sa.Column('otros_antecedentes', sa.String(), nullable=True),
    sa.Column('asa', sa.String(), nullable=True),
    sa.Column('funcional', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email_paciente', sa.String(), nullable=True),
    sa.Column('medico', sa.String(), nullable=True),
    sa.Column('medico_id', sa.String(), nullable=True),
    sa.Column('historia_clinica', sa.String(), nullable=True),
    sa.Column('eoss_metabolico', sa.Integer(), nullable=True),
    sa.Column('eoss_mecanico', sa.Integer(), nullable=True),
    sa.Column('eoss_psico', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###